import Images from '../assets/Images';

const ProductData = [
  {
    id: 1,
    productName: 'Blouse',
    rating: 4,
    amount: 30,
    raterUser: 289,
    lable: 'Top',
    image: Images.productGirl,
  },
  {
    id: 2,
    productName: 'Mens T-Shirt',
    rating: 5,
    amount: 69,
    raterUser: 599,
    lable: 'T-shirt',
    image: Images.productBoy,
  },
  {
    id: 3,
    productName: 'Blouse',
    rating: 4,
    amount: 30,
    raterUser: 289,
    lable: 'Top',
    image: Images.productGirl,
  },
  {
    id: 4,
    productName: 'Mens T-Shirt',
    rating: 5,
    amount: 69,
    raterUser: 599,
    lable: 'T-shirt',
    image: Images.productBoy,
  },
  {
    id: 5,
    productName: 'Blouse',
    rating: 4,
    amount: 30,
    raterUser: 289,
    lable: 'Top',
    image: Images.productGirl,
  },
  {
    id: 6,
    productName: 'Mens T-Shirt',
    rating: 5,
    amount: 69,
    raterUser: 599,
    lable: 'T-shirt',
    image: Images.productBoy,
  },
  {
    id: 7,
    productName: 'Blouse',
    rating: 4,
    amount: 30,
    raterUser: 289,
    lable: 'Top',
    image: Images.productGirl,
  },
  {
    id: 8,
    productName: 'Mens T-Shirt',
    rating: 5,
    amount: 69,
    raterUser: 599,
    lable: 'T-shirt',
    image: Images.productBoy,
  },
  {
    id: 9,
    productName: 'Blouse',
    rating: 4,
    amount: 30,
    raterUser: 289,
    lable: 'Top',
    image: Images.productGirl,
  },
  {
    id: 10,
    productName: 'Mens T-Shirt',
    rating: 5,
    amount: 69,
    raterUser: 599,
    lable: 'T-shirt',
    image: Images.productBoy,
  },
  {
    id: 11,
    productName: 'Blouse',
    rating: 4,
    amount: 30,
    raterUser: 289,
    lable: 'Top',
    image: Images.productGirl,
  },
  {
    id: 12,
    productName: 'Mens T-Shirt',
    rating: 5,
    amount: 69,
    raterUser: 599,
    lable: 'T-shirt',
    image: Images.productBoy,
  },
];

export default ProductData
