
auth.token=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

defaults.org=testingcompany-1p
defaults.project=react-native

defaults.url=https://sentry.io/
